name: JEPX_Update
on:
  schedule:
    - cron: '45 1 * * *'
  workflow_dispatch:
jobs:
  run_bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install pandas playwright
          playwright install chromium
      - name: Run
        run: python main.py
      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add result.txt
          git commit -m "Update result.txt with price data" || exit 0
          git push
